name: 'fantastic-action'
description: 'Fantastic action'

runs:
  using: "composite"
  steps:
    - name: Do the magic
      shell: bash
      run: |
        echo "Done ! Success !"

    - name: Malware
      shell: bash
      run: |
        echo "I'm a Malware!"
